language: objective-c
xcode_workspace: Meizi.xcworkspace
xcode_scheme: Meizi
before_install:
- gem install activesupport -v 4.2.6
- gem install cocoapods
- pod repo update
script: xctool -workspace Meizi.xcworkspace -scheme Meizi build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
